[2023-06-06 11:12:46,465] [citros.citros-None-None.login:273] [INFO]: Authenticated!
[2023-06-06 11:12:51,898] [citros.citros-None-None.get_project_packages:257] [DEBUG]:  + get_project_packages ./
[2023-06-06 11:12:51,901] [citros.citros-None-None.get_git_remote_url:362] [INFO]: Inside devcontainer. Cannot communicate with github.
[2023-06-06 11:12:51,901] [citros.citros-None-None.get_file_content:403] [ERROR]: could not find file ./LICENSE
[2023-06-06 11:13:32,462] [citros.citros-None-None.get_project_packages:257] [DEBUG]:  + get_project_packages ./
[2023-06-06 11:13:32,465] [citros.citros-None-None.get_git_remote_url:362] [INFO]: Inside devcontainer. Cannot communicate with github.
[2023-06-06 11:14:03,024] [citros.citros-None-None.get_project_packages:257] [DEBUG]:  + get_project_packages ./
[2023-06-06 11:14:03,028] [citros.citros-None-None.get_git_remote_url:362] [INFO]: Inside devcontainer. Cannot communicate with github.
[2023-06-06 11:15:08,596] [citros.citros-None-None.get_project_packages:257] [DEBUG]:  + get_project_packages ./
[2023-06-06 11:15:08,596] [citros.citros-None-None.get_project_packages:257] [DEBUG]:  + get_project_packages ./ros2_ws
[2023-06-06 11:15:08,596] [citros.citros-None-None.get_project_packages:268] [DEBUG]: package_path: ./ros2_ws/src/uros
[2023-06-06 11:15:08,596] [citros.citros-None-None.get_project_packages:268] [DEBUG]: package_path: ./ros2_ws/src/px4_ros_com
[2023-06-06 11:15:08,605] [citros.citros-None-None.get_project_packages:311] [ERROR]: [Errno 2] No such file or directory: './ros2_ws/src/px4_ros_com/config/params.yaml'
Traceback (most recent call last):
  File "/home/ros/.local/lib/python3.10/site-packages/citros/parsers/parser_ros2.py", line 294, in get_project_packages
    with open(path_to_config, 'r') as config_file:
FileNotFoundError: [Errno 2] No such file or directory: './ros2_ws/src/px4_ros_com/config/params.yaml'
[2023-06-06 11:15:08,606] [citros.citros-None-None.get_project_packages:268] [DEBUG]: package_path: ./ros2_ws/src/world_config
